name: 'Validate changes with deployment'
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    paths:
      - 'src/**'
      - 'src-org-dependent/**'
      - 'devops-scripts/**'
      - '.github/workflows/**'
    branches:
      - 'develop'
  merge_group:
    types: [ checks_requested ]

jobs:
  validate-max-qa:
    name: 'Validate MaxQA Deployment'
    uses: ./.github/workflows/validate-deploy-to-maxqa-on-pr.yml
    with:
      environment: 'MaxQA'
    secrets: inherit

  validate-ci-org:
    name: 'Ci-Org Validation'
    uses: ./.github/workflows/pr-ci-org-validation.yml
    secrets: inherit

  deploy-to-maxqa:
    name: 'Deploy to MAxQA'
    needs:
      - validate-max-qa
      - validate-ci-org
    runs-on: ubuntu-latest
    steps:
      - name: Deploy for PRs
        if: github.event_name == 'pull_request'
        run: echo "Ready to deploy"

      - name: Deploy for Merge Groups
        if: github.event_name == 'merge_group'
        uses: ./.github/workflows/deploy-to-maxqa-after-pr-close.yml
        secrets: inherit
