name: 'PR Open/Update Triggered - Validate Deploy to MaxQA'
on:
  workflow_call:
    inputs:
      environment:
        description: Environment
        type: string
        required: true

jobs:
  get-changed-modules:
    outputs:
      changed_modules: ${{ steps.detect_changes.outputs.changed_modules }}
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Changed Packages
        id: detect_changes
        run: |
          chmod +x ./devops-scripts/findChangedModules.sh
          ./devops-scripts/findChangedModules.sh

#  validate-changes:
#    name: 'Validate Deployment'
#    needs:
#      - get-changed-modules
#    uses: ./.github/workflows/validate-manual.yml
#    with:
#      environment: ${{ inputs.environment }}
#      modules_to_validate: ${{ needs.get-changed-modules.outputs.changed_modules }}
#      base_ref: 'origin/develop'
#    secrets: inherit