name: 'PR Open/Update Triggered - Validate Deploy to MaxQA'
on:
  workflow_call:
    inputs:
      environment:
        description: Environment
        type: string
        required: true

jobs:
  get-changed-modules:
    outputs:
      changed_modules: ${{ steps.detect_changes.outputs.changed_modules }}
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Changed Packages
        id: detect_changes
        run: |
          chmod +x ./devops-scripts/findChangedModules.sh
          ./devops-scripts/findChangedModules.sh

  validate-changes:
    name: 'Validate Deployment'
    needs:
      - get-changed-modules
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "Validate with PR workflow..."
            gh workflow run .github/workflows/deploy-to-maxqa-after-pr-close.yml
          elif [ "${{ github.event_name }}" == "merge_group" ]; then
            echo "Validatedc done..."
          fi
