name: 'Manual Validation'

on:
  workflow_call:
    secrets:
        SFDX_AUTH_URL:
          required: false
    inputs:
      environment:
        description: Environment
        type: string
        required: true
      parent_event:
        description: Event name
        type: string

jobs:
  validate-changes:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      WORKING_BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install JS dependencies
        run: echo "Installing JS dependencies..."

      - name: Validate Changes on ${{ inputs.environment }}
        id: validate_changes
        run: |
          echo "event name"
          echo ${{ inputs.parent_event }}
          echo "child event: $GITHUB_EVENT_NAME"
          echo "Run validation..."   
